"""File-only regression tests; never contact the desktop session."""
import os
from pathlib import Path
import subprocess
import tempfile
import unittest

ROOT = Path(__file__).resolve().parents[1]


class GtkThemesTest(unittest.TestCase):
    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory()
        self.addCleanup(self.tmp.cleanup)
        self.home = Path(self.tmp.name)
        self.env = dict(os.environ, HOME=str(self.home),
                        XDG_DATA_HOME=str(self.home / 'data'))
        self.generated = self.home / 'generated'
        (self.generated / 'gtk').mkdir(parents=True)
        for mode in ('dark', 'light'):
            (self.generated / 'gtk' / f'{mode}.theme').write_text(
                '/* GTK theme overrides - auto-generated by theme-manager from colors.json */\n'
                f'/* {mode} test palette */\n')

    def shell(self, script):
        return subprocess.run(
            ['bash', '-c', 'source "$1"; GENERATED_DIR="$2"; generate_tool_theme() { :; }; ' + script,
             'test', str(ROOT / 'theme-manager.sh'), str(self.generated)],
            env=self.env, text=True, capture_output=True, check=True).stdout

    def apply(self, mode):
        self.shell(f'apply_tool_theme gtk {mode}')

    def test_named_themes_for_both_modes_and_gtk_versions(self):
        for mode in ('dark', 'light'):
            self.apply(mode)
            for version, base in ((3, 'Adwaita'), (4, 'Default')):
                directory = self.home / f'data/themes/ThemesGenerator/gtk-{version}.0'
                variant = '-dark' if mode == 'dark' else ''
                css = (directory / f'gtk{variant}.css').read_text()
                self.assertIn(f'/theme/{base}/gtk{variant}.css', css)
                self.assertIn(f'{mode} test palette', css)
                self.assertNotEqual((directory / 'gtk.css').read_text(),
                                    (directory / 'gtk-dark.css').read_text())
                settings = self.home / f'.config/gtk-{version}.0/settings.ini'
                self.assertIn('gtk-theme-name=ThemesGenerator', settings.read_text())
                self.assertFalse(settings.with_name('gtk.css').exists())

    def test_generated_override_backed_up_once(self):
        directory = self.home / '.config/gtk-3.0'
        directory.mkdir(parents=True)
        legacy = directory / 'gtk.css'
        original = (self.generated / 'gtk/dark.theme').read_text()
        legacy.write_text(original)
        self.apply('light')
        self.apply('dark')
        backups = list(directory.glob('gtk.css.pre-named-theme.*'))
        self.assertEqual(len(backups), 1)
        self.assertEqual(backups[0].read_text(), original)
        self.assertFalse(legacy.exists())

    def test_custom_css_and_symlinks_preserved(self):
        for version in (3, 4):
            (self.home / f'.config/gtk-{version}.0').mkdir(parents=True)
        custom = self.home / '.config/gtk-3.0/gtk.css'
        custom.write_text('/* user CSS */')
        linked = self.home / '.config/gtk-4.0/gtk.css'
        linked.symlink_to(self.home / 'missing-user-theme.css')
        self.apply('dark')
        self.assertEqual(custom.read_text(), '/* user CSS */')
        self.assertTrue(linked.is_symlink())

    def test_generation_failure_does_not_retire_existing_css(self):
        directory = self.home / '.config/gtk-3.0'
        directory.mkdir(parents=True)
        legacy = directory / 'gtk.css'
        original = (self.generated / 'gtk/dark.theme').read_text()
        legacy.write_text(original)
        with self.assertRaises(subprocess.CalledProcessError):
            self.shell('generate_tool_theme() { return 1; }; apply_tool_theme gtk dark')
        self.assertEqual(legacy.read_text(), original)

    def test_signal_keeps_theme_name_stable(self):
        output = self.shell('''
dconf() { printf '%s\\n' "$*"; }
signal_color_scheme light
signal_color_scheme dark
''')
        self.assertEqual(output.count("write /org/gnome/desktop/interface/gtk-theme 'ThemesGenerator'"), 2)
        self.assertIn("color-scheme 'prefer-light'", output)
        self.assertIn("color-scheme 'prefer-dark'", output)

    def test_gtk_installed_before_preference_signal(self):
        output = self.shell('''
set_theme_mode() { :; }
generate_tool_theme() { :; }
apply_tool_theme() { printf 'apply:%s\\n' "$1"; }
signal_color_scheme() { echo signal; }
generate_all() { :; }
apply_all() { :; }
apply_system_theme() { :; }
restart_electron_apps() { :; }
switch_theme dark
''')
        self.assertLess(output.index('apply:gtk'), output.index('signal'))


if __name__ == '__main__':
    unittest.main()
